spring.application.name=form
server.port=8080
spring.mongodb.uri=mongodb+srv://sawankumarlad2005_db_user:SaWaN310705@cluster0.r45saci.mongodb.net/form
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sawankumarlad2005@gmail.com
spring.mail.password=vdnvcmrtojtjezoj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
